Update smoke-test-job.yaml

diff --git a/k8s/smoke-test-job.yaml b/k8s/smoke-test-job.yaml
--- a/k8s/smoke-test-job.yaml
+++ b/k8s/smoke-test-job.yaml
@@ -2,27 +2,33 @@ apiVersion: batch/v1
 kind: Job
 metadata:
   name: todo-smoke-test
+  namespace: staging
 spec:
-  backoffLimit: 1
   template:
     spec:
       containers:
       - name: curl
         image: curlimages/curl:7.88.1
         command:
-        - sh
-        - -c
-        - |
-          # attempt curl internal service
-          echo "Waiting for service..."
-          for i in $(seq 1 20); do
-            sleep 3
-            if curl -sS http://todo-service:3000/ | grep -q "My To-Do List"; then
-              echo "smoke test success"
-              exit 0
-            fi
-          done
-          echo "smoke test failed"
-          exit 1
+          - sh
+          - -c
+          - |
+            echo "Waiting for service..."
+            for i in $(seq 1 20); do
+              sleep 3
+              if curl -sS http://todo-service:3000/ | grep -q "My To-Do List"; then
+                echo "smoke test success"
+                exit 0
+              fi
+            done
+            echo "smoke test failed"
+            exit 1
+        resources:
+          requests:
+            cpu: "50m"
+            memory: "64Mi"
+          limits:
+            cpu: "100m"
+            memory: "128Mi"
       restartPolicy: Never
-
+  backoffLimit: 1
